services:
  - type: worker
    name: notion-task-processor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduled_service.py
    envVars:
      - key: NOTION_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false